
version: '2'
services:
  elasticsearch:
    image: meedan/elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch/config:/usr/share/elasticsearch/config
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/snapshots:/usr/share/elasticsearch/snapshots
      - ./elasticsearch/scripts:/usr/share/elasticsearch/scripts
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_DATABASE: checkdesk_production
  api.production:
    build:
      context: ./check-api
      dockerfile: Dockerfile.production
    command: /opt/bin/wait_and_start.sh
    ports:
      - 3000:80
    links:
      - elasticsearch
      - postgres
      - pender.production
    volumes:
      - ./check-api/config:/app/shared/config
      - ./check-api/public/uploads:/app/shared/files
    environment:
      PRIMARY: "true"
  pender.production:
    build:
      context: ./pender
      dockerfile: Dockerfile.production
    shm_size: 1G
    ports:
      - 3200:3200
      - 9555:9555
    volumes:
      - ./pender:/app
    environment:
      SERVER_PORT: 3200
      PRIMARY: "true"
  web.production:
    build:
      context: ./check-web
      dockerfile: docker/production/Dockerfile
    ports:
      - 3333:3333
    links:
      - api.production
    volumes:
      - ./check-web:/app
      - ./check-api:/api
      - /app/node_modules
    environment:
      SERVER_PORT: 3333
      PRIMARY: "true"
